-- MySQL Script generated by MySQL Workbench
-- Fri Jul 29 21:49:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_Marketplase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_Marketplase` ;

-- -----------------------------------------------------
-- Schema bd_Marketplase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_Marketplase` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema bd_Classificados
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema bd_E-Comerce
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_E-Comerce` ;

-- -----------------------------------------------------
-- Schema bd_E-Comerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_E-Comerce` ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema bd_Rede_Social
-- -----------------------------------------------------
SHOW WARNINGS;
USE `bd_Marketplase` ;

-- -----------------------------------------------------
-- Table `compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `compra` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `compra` (
  `date DATE` VARCHAR(45) NOT NULL,
  `tb_produtos_id_produto` INT NOT NULL,
  `tb_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`tb_produtos_id_produto`, `tb_usuario_id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `table1` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_compras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_compras` (
  `fk_comprador` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`fk_comprador`, `fk_produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_produtos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(100) NOT NULL,
  `valor` FLOAT NOT NULL,
  `estoque` INT NOT NULL,
  `categoria` ENUM('CAT1', 'CAT2') NOT NULL,
  `url_imagem` VARCHAR(100) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_produtos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(45) NOT NULL,
  `descrição` VARCHAR(100) NOT NULL,
  `valor` FLOAT NOT NULL,
  `estoque` INT NOT NULL,
  `categoria` ENUM('CAT1', 'CAT2') NOT NULL,
  `url_imagem` VARCHAR(100) NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `url_foto` VARCHAR(100) NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_usuarios` (
  `id_usuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `url_foto` VARCHAR(100) NULL,
  PRIMARY KEY (`id_usuarios`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `td_anuncios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `td_anuncios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `td_anuncios` (
  `id_anuncio` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `contato` VARCHAR(50) NOT NULL,
  `url_imagem` VARCHAR(100) NULL,
  `data` DATE NOT NULL,
  `tb_usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_anuncio`, `tb_usuarios_id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `bd_E-Comerce` ;

-- -----------------------------------------------------
-- Table `table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `table1` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `table1` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_grupos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_grupos` (
  `id_grupos` INT NOT NULL,
  `grupo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `url_imagem` VARCHAR(100) NULL,
  `fk_criador` INT NULL,
  `tb_usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_grupos`, `tb_usuarios_id_usuarios`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_inscritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_inscritos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_inscritos` (
  `date` DATE NOT NULL,
  `tb_usuarios_id_usuarios` INT NOT NULL,
  `tb_grupos_id_grupos` INT NOT NULL,
  PRIMARY KEY (`tb_usuarios_id_usuarios`, `tb_grupos_id_grupos`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_postagens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_postagens` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_postagens` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(1000) NOT NULL,
  `valor` FLOAT NOT NULL,
  `estoque` INT NOT NULL,
  `categoria` ENUM('CAT1', 'CAT2') NOT NULL,
  `url_imagem` VARCHAR(100) NULL,
  `tb_usuarios_id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id_postagem`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
