-- MySQL Script generated by MySQL Workbench
-- Thu Jul 28 21:14:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_Marketplase
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_Marketplase` ;

-- -----------------------------------------------------
-- Schema db_Marketplase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_Marketplase` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `db_Marketplase` ;

-- -----------------------------------------------------
-- Table `tb_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_compras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_compras` (
  `fk_comprador` INT NOT NULL,
  `fk_produto` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`fk_comprador`, `fk_produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_produtos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_produtos` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `tb_usuario` INT NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tb_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tb_usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
